```typescript
export const LEVELS = [
  { level: 1,  xp: 0,      title: 'Rift Novice',            unlocks: 'Basic Scan' },
  { level: 2,  xp: 100,    title: 'Rift Watcher',           unlocks: 'Lock Attempts' },
  { level: 3,  xp: 250,    title: 'Signal Tracer',          unlocks: 'Wormhole Map' },
  { level: 4,  xp: 450,    title: 'Static Listener',        unlocks: 'Solo Lens Preview' },
  { level: 5,  xp: 700,    title: 'Back Door Spotter',      unlocks: 'Open First Door' },
  { level: 6,  xp: 1000,   title: 'Threshold Walker',       unlocks: 'Longer Door Duration' },
  { level: 7,  xp: 1400,   title: 'Anomaly Hunter',         unlocks: 'Dual Glitch Scan' },
  { level: 8,  xp: 1900,   title: 'Dimensional Scout',      unlocks: 'AR Solo Lens' },
  { level: 9,  xp: 2500,   title: 'Echo Interpreter',       unlocks: 'Source Code Hints' },
  { level: 10, xp: 3200,   title: 'Reality Surveyor',       unlocks: 'Wormhole Stabilizer' },
  { level: 11, xp: 4000,   title: 'Rift Diver',             unlocks: 'Enhanced AR' },
  { level: 12, xp: 5000,   title: 'Ghost Architect',        unlocks: 'Two Simultaneous Doors' },
  { level: 13, xp: 6200,   title: 'Code Whisperer',         unlocks: 'Full Secrets' },
  { level: 14, xp: 7600,   title: 'Solo Wanderer',          unlocks: 'Weather Control' },
  { level: 15, xp: 9200,   title: 'Deep Reality Hacker',    unlocks: 'Source Code Edits' },
  { level: 16, xp: 11000,  title: 'Dimensional Engineer',   unlocks: 'Nested Doors' },
  { level: 17, xp: 13000,  title: 'Back Door Keeper',       unlocks: 'Auto‑Seal' },
  { level: 18, xp: 15200,  title: 'Loneliness Savant',      unlocks: 'Time Dilation' },
  { level: 19, xp: 17600,  title: 'Seal Breaker',           unlocks: 'Ultra Stability' },
  { level: 20, xp: 20200,  title: 'Reality Editor',         unlocks: 'Cosmic Filter' },
  { level: 21, xp: 23000,  title: 'Master Hacker',          unlocks: 'Blind Scan' },
  { level: 22, xp: 26000,  title: 'Primal Walker',          unlocks: 'Primal Back Door Preview' },
  { level: 23, xp: 29200,  title: 'Code Conduit',           unlocks: 'Instant Translate' },
  { level: 24, xp: 32600,  title: 'Omni‑Door',              unlocks: 'Any Environment' },
  { level: 25, xp: 36200,  title: 'Lens Ascendant',         unlocks: 'Life Erasure Supreme' },
  { level: 26, xp: 40000,  title: 'Glitch Prophet',         unlocks: 'Predict Glitches' },
  { level: 27, xp: 44000,  title: 'Dimension Lord',         unlocks: 'Create Temporary Door' },
  { level: 28, xp: 48200,  title: 'Source Architect',       unlocks: 'Write Secrets' },
  { level: 29, xp: 52600,  title: 'Back Door Deity',        unlocks: 'All Doors Open' },
  { level: 30, xp: 57200,  title: 'Architect of the Back Doors', unlocks: 'Primal Back Door' },
];
```